FROM php:8.4-apache

# dependencias para MySQL 9.5
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    default-libmysqlclient-dev \
    libssl-dev \
    && docker-php-ext-install mysqli pdo_mysql \
    && docker-php-ext-enable mysqli pdo_mysql

# rewrite en Apache
RUN a2enmod rewrite

COPY . /var/www/html/
