
services:
  web-003:
    image: php:8.4-apache
    container_name: web-003-jonathan
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
  mysql-003:
    image: mysql:9.5.0
    container_name: mysql-003-jonathan
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3366:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
